# Generated by Django 3.2.7 on 2021-10-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_test', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images//%Y/%m/%d')),
                ('contactNumber', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_facility', to='lab_test.labtest')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FacilityStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Staffs',
            },
        ),
        migrations.CreateModel(
            name='FacilityAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_admins', to='facilities.facility')),
                ('staff', models.ManyToManyField(to='facilities.FacilityStaff')),
            ],
            options={
                'verbose_name_plural': 'Facility Admins',
            },
        ),
    ]
