# Generated by Django 3.2.7 on 2021-10-05 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facilityadmin_facilitystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, upload_to='images//%Y/%m/%d'),
        ),
    ]
