# Generated by Django 3.2.7 on 2021-10-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211007_1243'),
        ('facilities', '0002_remove_facility_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facility_staff', to='authentication.staff'),
            preserve_default=False,
        ),
    ]
