# Generated by Django 3.2.7 on 2021-10-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitystaff',
            name='facility',
        ),
        migrations.DeleteModel(
            name='FacilityAdmin',
        ),
        migrations.DeleteModel(
            name='FacilityStaff',
        ),
    ]
