# Generated by Django 3.2.7 on 2021-10-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211010_2319'),
        ('facilities', '0004_auto_20211008_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_staff', to='authentication.customuser'),
        ),
    ]
