# Generated by Django 3.2.7 on 2021-10-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_facility_staff',
        ),
    ]
