# Generated by Django 3.2.7 on 2021-10-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_facility_staff'),
        ('authentication', '0005_auto_20211010_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
