# Generated by Django 3.2.7 on 2021-10-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_types', to='authentication.user_type'),
            preserve_default=False,
        ),
    ]
