# Generated by Django 3.2.7 on 2021-10-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_user_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_types',
        ),
    ]
