# Generated by Django 3.2.7 on 2021-10-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_customuser_user_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_fac_staff',
            field=models.BooleanField(default=False, verbose_name='Facility status'),
        ),
        migrations.DeleteModel(
            name='user_type',
        ),
    ]
