# Generated by Django 3.2.7 on 2021-10-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20211012_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_fac_staff',
            field=models.BooleanField(default=False),
        ),
    ]
