# Generated by Django 3.2.7 on 2021-10-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0003_auto_20211005_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('testId', models.AutoField(primary_key=True, serialize=False)),
                ('testName', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('image', models.ImageField(blank=True, upload_to='images/test//%Y/%m/%d')),
                ('active_status', models.CharField(choices=[('Available', 'AVAILABLE'), ('Closed', 'CLOSED')], default='AVAILABLE', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_facility', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['-testId'],
            },
        ),
    ]
