# Generated by Django 3.2.7 on 2021-10-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='images/test//%Y/%m/%d')),
                ('active_status', models.CharField(choices=[('Available', 'AVAILABLE'), ('Closed', 'CLOSED')], default='AVAILABLE', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentType', models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Half Payment', 'Half Payment')], default='Full Payment', max_length=20, null=True)),
                ('paymentMethod', models.CharField(blank=True, choices=[('MPESA', 'Mpesa'), ('CREDIT CARD', 'Credit Card'), ('ON ARRIVAL', 'On Arrival')], max_length=20, null=True)),
                ('bookedTimeSlot', models.CharField(blank=True, choices=[('10:00 AM - 2:00 PM', '10:00 AM - 2:00 PM'), ('3:00 PM - 7:00 PM', '3:00 PM - 7:00 PM'), ('8:00 PM - 10:00 PM', '8:00 PM - 10:00 PM')], max_length=20, null=True)),
                ('bookedDate', models.DateField(blank=True, null=True)),
                ('order_created_at', models.TimeField(auto_now=True)),
                ('staffChecking', models.BooleanField(default=False)),
                ('adminApprove', models.BooleanField(default=False)),
                ('orderConfirmed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('validation', models.BooleanField(default=False)),
                ('clientTested', models.BooleanField(default=False)),
                ('clientInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_test_user', to='authentication.profile')),
                ('testInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_order', to='lab_test.labtest')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
