# Generated by Django 3.2.7 on 2021-10-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_remove_facility_lab'),
        ('lab_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test', to='facilities.facility'),
            preserve_default=False,
        ),
    ]
