# Generated by Django 3.2.7 on 2021-10-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_test', '0002_labtest_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='lab',
            new_name='facility',
        ),
    ]
